import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'IT' | 'EN';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  IT: {
    'nav.signature': 'PRESTIGE',
    'nav.urban': 'LIVING',
    'nav.trackrecord': 'REALIZZAZIONI',
    'nav.intelligence': 'INTELLIGENCE',
    'nav.method': 'CHI SIAMO',
    'nav.contact': 'Contatti',

    'hero.title': 'Costruiamo Valore, Progettiamo il Domani',
    'hero.techBadge': 'Native AI & Domotica Standard',
    'hero.cta': 'Scopri le Collezioni',

    'collection.techBadge': 'Travelli Intelligence Integrated',

    'home.intro': 'Oltre il General Contractor. Trasformiamo visioni architettoniche in asset immobiliari duraturi.',

    'projects.title': 'Progetti in Evidenza',
    'projects.subtitle': 'Portfolio selezionato di sviluppi immobiliari di eccellenza',
    'projects.signature.status': 'PRESTIGE COLLECTION',
    'projects.villa.tagline': 'Qualità che si vive!',
    'projects.villa.desc': 'Un restauro magistrale che fonde storia e comfort moderno sulle colline fiorentine.',
    'projects.casa.tagline': 'Vivere oltre lo standard',
    'projects.casa.desc': 'Residenza esclusiva nel cuore della città, dove design incontra arte.',
    'projects.borgo.tagline': 'In Consegna 2026',
    'projects.borgo.desc': 'Un complesso residenziale immerso nella natura, alle porte del Chianti.',

    'method.title': 'Il Metodo Travelli',
    'method.subtitle': 'Un approccio integrato che unisce visione architettonica, rigore finanziario e eccellenza operativa',
    'method.acquisition': 'Acquisizione',
    'method.acquisition.desc': 'Identificazione strategica di opportunità immobiliari ad alto potenziale.',
    'method.design': 'Progettazione',
    'method.design.desc': 'Collaborazione con studi di architettura di prestigio per visioni uniche.',
    'method.construction': 'Sviluppo',
    'method.construction.desc': 'Gestione integrata del processo costruttivo con i massimi standard qualitativi.',
    'method.management': 'Asset Management',
    'method.management.desc': 'Valorizzazione continua e gestione patrimoniale a lungo termine.',
    'method.since': 'Dal 2010',
    'method.value': 'Valore totale degli sviluppi realizzati',

    'method.hero.title': '30 Anni di Costruzioni e Sviluppo',
    'method.hero.subtitle': 'Un\'eredità di eccellenza costruttiva che guarda al futuro',
    'method.stats.years': 'Anni di Storia',
    'method.stats.projects': 'Progetti Completati',
    'method.stats.delivered': 'Consegnati in Tempo',
    'method.roots.label': 'LA NOSTRA STORIA',
    'method.roots.title': 'Le Nostre Radici',
    'method.roots.text1': 'Fondata nel 1994, Travelli ha attraversato tre decenni di evoluzione immobiliare. Da impresa di costruzioni focalizzata sul restauro conservativo a Developer integrato.',
    'method.roots.text2': 'La nostra esperienza si estende dal recupero di edifici storici vincolati alla realizzazione di complessi residenziali moderni, mantenendo sempre il massimo rigore tecnico e attenzione al dettaglio che ci contraddistingue.',
    'method.restoration.title': 'Il Restauro Conservativo',
    'method.restoration.subtitle': 'La nostra specializzazione nei beni vincolati e nel recupero storico',
    'method.restoration.quote': 'Recuperare il passato richiede più tecnica del costruire il nuovo. La nostra esperienza sui beni vincolati è la garanzia della nostra qualità costruttiva.',
    'method.restoration.expertise1.title': 'Beni Vincolati',
    'method.restoration.expertise1.desc': 'Esperienza trentennale nel restauro di edifici sottoposti a vincolo monumentale e paesaggistico, nel rispetto delle normative della Soprintendenza.',
    'method.restoration.expertise2.title': 'Tecniche Tradizionali',
    'method.restoration.expertise2.desc': 'Maestranze specializzate nelle tecniche costruttive storiche, dallo stucco veneziano alle decorazioni in affresco.',
    'method.restoration.expertise3.title': 'Comfort Moderno',
    'method.restoration.expertise3.desc': 'Integrazione invisibile di impianti e tecnologie moderne nel rispetto delle strutture originali e del contesto storico.',
    'method.restoration.expertise4.title': 'Valorizzazione',
    'method.restoration.expertise4.desc': 'Trasformazione di edifici storici in asset immobiliari di pregio, preservandone il valore culturale e aumentandone quello economico.',
    'method.governance.label': 'LEADERSHIP',
    'method.governance.title': 'Continuità e Visione',
    'method.governance.subtitle': 'Un team di professionisti con decenni di esperienza nel settore immobiliare',
    'method.governance.team': 'Un organico di 50 professionisti dedicati all\'eccellenza',

    'method.board.title': 'The Board',
    'method.board.subtitle': 'La Famiglia Travelli',
    'method.board.roberto.name': 'Roberto Travelli',
    'method.board.roberto.title': 'Fondatore',
    'method.board.roberto.desc': 'È l\'inizio della storia Travelli. Rappresenta le radici solide da cui l\'azienda è nata. La sua etica del lavoro costituisce oggi il DNA morale dell\'azienda e l\'impronta indelebile che guida le nuove generazioni.',
    'method.board.enrico.name': 'Enrico Travelli',
    'method.board.enrico.title': 'CEO & Head of Development',
    'method.board.enrico.desc': 'L\'evoluzione dinamica del brand. Guida la strategia di sviluppo portando una visione internazionale. Il suo focus è trasformare gli spazi in esperienze abitative uniche, integrando design contemporaneo, sostenibilità e tecnologie smart.',
    'method.board.elisa.name': 'Elisa Travelli',
    'method.board.elisa.title': 'CFO & Finanza e Controllo',
    'method.board.elisa.desc': 'Il governo dei numeri e della strategia. Garantisce la solidità economica dell\'azienda e di ogni singola operazione. La sua pianificazione rigorosa assicura che ogni progetto poggi su basi finanziarie trasparenti, concrete e sostenibili.',

    'method.structure.label': 'LA NOSTRA FORZA',
    'method.structure.title': '50 Dipendenti Diretti',
    'method.structure.subtitle': 'La garanzia della qualità e dei tempi certi',
    'method.structure.desc1': 'A differenza di molti operatori del settore, Travelli può contare su un organico di 50 dipendenti diretti. Non subappalti, non collaborazioni occasionali: un team stabile e dedicato.',
    'method.structure.desc2': 'Questo significa controllo totale su ogni fase del progetto, dalla progettazione alla consegna. Significa tempi certi, qualità costante, e la certezza che ogni dettaglio riceva l\'attenzione che merita.',
    'method.structure.benefit1': 'Controllo Qualità Totale',
    'method.structure.benefit1.desc': 'Ogni lavorazione è svolta da personale interno formato e certificato',
    'method.structure.benefit2': 'Tempi Garantiti',
    'method.structure.benefit2.desc': 'Nessuna dipendenza da fornitori esterni o ritardi imprevisti',
    'method.structure.benefit3': 'Responsabilità Diretta',
    'method.structure.benefit3.desc': 'Un unico interlocutore per l\'intero processo costruttivo',

    'method.process.label': 'IL NOSTRO APPROCCIO',
    'method.process.title': 'Il Metodo Integrato',
    'method.process.subtitle': 'Dall\'acquisizione alla vendita: un processo completo',
    'method.process.step1': 'Acquisizione',
    'method.process.step1.desc': 'Identificazione strategica di opportunità immobiliari ad alto potenziale in location premium',
    'method.process.step2': 'Progettazione',
    'method.process.step2.desc': 'Sviluppo architettonico con studi di prestigio, massimizzando valore e vivibilità',
    'method.process.step3': 'Costruzione',
    'method.process.step3.desc': 'Realizzazione con maestranze interne, controllo qualità costante e tempi certi',
    'method.process.step4': 'Commercializzazione',
    'method.process.step4.desc': 'Vendita diretta con assistenza personalizzata dalla visita al rogito',

    'method.team.label': 'MANAGEMENT & OPERATIVITÀ',
    'method.team.title': 'Management & Coordinamento',
    'method.team.subtitle': 'Una struttura organizzativa che coordina oltre 50 dipendenti diretti. Il nostro management garantisce il controllo totale di ogni fase, dall\'acquisto dei materiali alla consegna delle chiavi.',
    'method.team.coo.title': 'Direttore Operativo (COO)',
    'method.team.coo.desc': 'Supervisione generale dei cantieri e coordinamento delle squadre operative.',
    'method.team.pm.title': 'Senior Project Manager',
    'method.team.pm.desc': 'Gestione tecnica delle commesse complesse e interfaccia con la Direzione Lavori.',
    'method.team.sales.title': 'Sales Manager',
    'method.team.sales.desc': 'Responsabile della commercializzazione e della customer experience.',
    'method.team.procurement.title': 'Responsabile Acquisti (Procurement)',
    'method.team.procurement.desc': 'Selezione dei fornitori e controllo qualità dei materiali in ingresso.',
    'method.team.design.title': 'Head of Design',
    'method.team.design.desc': 'Sviluppo del concept architettonico e cura del dettaglio nelle finiture.',
    'method.team.safety.title': 'Responsabile Sicurezza & Qualità',
    'method.team.safety.desc': 'Garanzia del rispetto normativo e degli standard costruttivi Travelli.',

    'method.management.title': 'Key Management',
    'method.management.subtitle': 'I Leader Operativi',
    'method.management.coo.name': 'Ing. [Nome Cognome]',
    'method.management.coo.title': 'Direttore Operativo (COO)',
    'method.management.coo.desc': 'Coordina le squadre operative e la logistica dei nostri 50 collaboratori, garantendo tempi certi e sicurezza in cantiere.',
    'method.management.pm.name': 'Ing. [Nome Cognome]',
    'method.management.pm.title': 'Senior Project Manager',
    'method.management.pm.desc': 'Il raccordo tra progettazione ed esecuzione. Gestisce la complessità burocratica e tecnica di ogni commessa.',
    'method.management.sales.name': '[Nome Cognome]',
    'method.management.sales.title': 'Sales Manager',
    'method.management.sales.desc': 'Accompagna i nostri clienti dalla prima visita al rogito, offrendo un\'assistenza dedicata e personalizzata.',

    'footer.subscribe': 'Iscriviti',
    'footer.insights': 'Ricevi analisi di mercato e opportunità esclusive',
    'footer.navigation': 'Navigazione',
    'footer.home': 'Home',
    'footer.collections': 'Collezioni',
    'footer.company': 'Azienda',
    'footer.about': 'Chi Siamo',
    'footer.careers': 'Carriere',
    'footer.privacy': 'Privacy Policy',
    'footer.cookies': 'Cookie Policy',
    'footer.legal': 'Note Legali',
    'footer.vat': 'P.IVA',

    'signature.title': 'TRAVELLI PRESTIGE',
    'signature.subtitle': "L'apice dell'abitare.",
    'signature.intro': "La collezione Prestige rappresenta l'eccellenza assoluta nel real estate di lusso. Progetti iconici che ridefiniscono il concetto di abitare esclusivo.",
    'signature.cta': 'Richiedi Private Viewing',
    'signature.appointment': 'Appuntamenti su invito • Consulenza riservata',

    'urban.title': 'TRAVELLI LIVING',
    'urban.subtitle': 'Il comfort contemporaneo nella città che cambia.',
    'urban.cta': 'SCOPRI I PROGETTI',
    'urban.section.title': 'I Nostri Complessi',
    'urban.section.subtitle': 'Residenze urbane progettate per lo stile di vita contemporaneo, dove tecnologia e comfort si incontrano.',
    'urban.concept.title': 'Il Concetto Living',
    'urban.concept.subtitle': 'Innovazione, sostenibilità e connettività al centro della nostra visione residenziale.',
    'urban.feature.sustainability': 'Sostenibilità',
    'urban.feature.sustainability.desc': 'Edifici certificati LEED con pannelli solari e sistemi di recupero energetico',
    'urban.feature.smart': 'Connessione Smart',
    'urban.feature.smart.desc': 'Domotica avanzata, fibra ottica e app di gestione integrata',
    'urban.feature.mobility': 'Mobilità Dolce',
    'urban.feature.mobility.desc': 'Bike sharing, colonnine elettriche e connessione metro/tram',
    'urban.project.cta': 'SCOPRI IL PROGETTO',
    'urban.visit.cta': 'PRENOTA UNA VISITA',

    'collection.signature.title': 'TRAVELLI\nPRESTIGE',
    'collection.signature.desc': "L'arte dell'abitare. Progetti unici, senza compromessi.",
    'collection.signature.cta': 'Scopri Prestige',
    'collection.urban.title': 'TRAVELLI\nLIVING',
    'collection.urban.desc': "L'evoluzione del vivere contemporaneo. Smart, connesso, essenziale.",
    'collection.urban.cta': 'Scopri Living',

    'intelligence.badge': 'TECNOLOGIA PROPRIETARIA',
    'intelligence.title': 'TRAVELLI INTELLIGENCE',
    'intelligence.subtitle': 'Oltre la Domotica. La casa che pensa insieme a te.',
    'intelligence.card1.title': 'Smart Living & Controllo',
    'intelligence.card1.desc': "Gestione totale degli ambienti. Luci, clima e sicurezza controllati da un'unica interfaccia intuitiva, ovunque tu sia.",
    'intelligence.card2.title': 'AI & Efficienza Energetica',
    'intelligence.card2.desc': 'Algoritmi predittivi che ottimizzano i consumi in base alle tue abitudini reali. Il lusso è non sprecare.',
    'intelligence.card3.title': 'Sicurezza Attiva',
    'intelligence.card3.desc': 'Sistemi di sorveglianza integrati e sensori ambientali per una protezione discreta ma costante.',
    'intelligence.cta': 'Scopri lo Standard Tecnologico',

    'intelligence.hero.title': 'Travelli Intelligence',
    'intelligence.hero.subtitle': 'La casa intelligente non è un optional. È lo standard in ogni nostro progetto.',

    'intelligence.features.title': 'Cosa Include il Sistema',
    'intelligence.features.subtitle': 'Una piattaforma completa di domotica integrata progettata per il comfort e la sicurezza quotidiana',
    'intelligence.features.climate.title': 'Climatizzazione Smart',
    'intelligence.features.climate.desc': 'Controllo temperatura ambiente per ambiente con algoritmi di risparmio energetico',
    'intelligence.features.lighting.title': 'Illuminazione Intelligente',
    'intelligence.features.lighting.desc': 'Scene luminose personalizzate e controllo da remoto per ogni stanza',
    'intelligence.features.security.title': 'Sicurezza Integrata',
    'intelligence.features.security.desc': 'Allarmi, videocamere e sensori di movimento gestiti in un unico sistema',
    'intelligence.features.entertainment.title': 'Audio/Video Multiroom',
    'intelligence.features.entertainment.desc': 'Intrattenimento distribuito in tutte le stanze con controllo centralizzato',
    'intelligence.features.energy.title': 'Monitoraggio Energetico',
    'intelligence.features.energy.desc': 'Tracciamento consumi in tempo reale e ottimizzazione automatica',
    'intelligence.features.app.title': 'App Mobile Dedicata',
    'intelligence.features.app.desc': 'Controllo completo da smartphone iOS e Android ovunque tu sia',
    'intelligence.features.scenes.title': 'Scene Predefinite',
    'intelligence.features.scenes.desc': 'Modalità Casa, Notte, Vacanza attivabili con un tocco',
    'intelligence.features.ai.title': 'Intelligenza Artificiale',
    'intelligence.features.ai.desc': 'Apprendimento delle tue abitudini per ottimizzare comfort ed efficienza',

    'intelligence.standard.title': 'Standard in Ogni Progetto',
    'intelligence.standard.subtitle': 'Non un costoso upgrade, ma parte integrante di ogni residenza Travelli. La tecnologia è il nuovo standard abitativo.',
    'intelligence.standard.point1.title': 'Pre-installato di Serie',
    'intelligence.standard.point1.desc': 'Ogni appartamento viene consegnato con il sistema completo già configurato e testato',
    'intelligence.standard.point2.title': 'Assistenza Dedicata',
    'intelligence.standard.point2.desc': 'Supporto tecnico e formazione personalizzata al momento della consegna',
    'intelligence.standard.point3.title': 'Aggiornamenti Continui',
    'intelligence.standard.point3.desc': 'Il sistema evolve nel tempo con nuove funzionalità via software',

    'intelligence.landing.hero.title': 'TRAVELLI INTELLIGENCE',
    'intelligence.landing.hero.subtitle': 'La tua casa è un organismo vivente. Un ecosistema integrato di AI e Domotica che impara, protegge e anticipa.',
    'intelligence.landing.nativo.title': 'NATIVO DIGITALE',
    'intelligence.landing.nativo.desc': 'A differenza della domotica tradizionale installata a posteriori, il sistema Travelli Intelligence è cablato nel DNA dell\'edificio in fase di costruzione. Invisibile, affidabile, eterno.',
    'intelligence.landing.services.title': 'I 4 PILASTRI DEL SISTEMA',
    'intelligence.landing.climate.title': 'Clima Predittivo',
    'intelligence.landing.climate.desc': 'L\'intelligenza artificiale incrocia i dati meteo in tempo reale con le tue abitudini. La casa si termoregola in anticipo, garantendo comfort perfetto e zero sprechi.',
    'intelligence.landing.circadian.title': 'Illuminazione Circadiana',
    'intelligence.landing.circadian.desc': 'La luce segue il ciclo biologico del sole. Toni freddi per l\'energia mattutina, toni caldi e ambrati per il relax serale. Per vivere in sintonia con il tuo ritmo naturale.',
    'intelligence.landing.monitor.title': 'Autodiagnostica Strutturale',
    'intelligence.landing.monitor.desc': 'Sensori integrati monitorano costantemente impianti idrici ed elettrici. Il sistema rileva anomalie e micro-perdite inviando alert preventivi prima che diventino guasti.',
    'intelligence.landing.security.title': 'Sicurezza Attiva',
    'intelligence.landing.security.desc': 'Il sistema distingue tra ospiti, familiari e intrusi. Scenari di presenza simulata quando sei in vacanza per dissuadere ogni intenzione esterna.',
    'intelligence.landing.cta.text': 'Il futuro è già capitolato.',
    'intelligence.landing.cta.button': 'Richiedi Capitolato Tecnico',

    'trackrecord.hero.title': '30 Anni di Eccellenza',
    'trackrecord.hero.subtitle': 'Dal restauro conservativo alle nuove costruzioni. La nostra storia costruita pietra su pietra.',
    'trackrecord.filter.all': 'TUTTI',
    'trackrecord.filter.restauro': 'RESTAURO CONSERVATIVO',
    'trackrecord.filter.residenziale': 'RESIDENZIALE',
    'trackrecord.category.restauro': 'Restauro Storico',
    'trackrecord.category.residenziale': 'Nuova Costruzione',
  },
  EN: {
    'nav.signature': 'PRESTIGE',
    'nav.urban': 'LIVING',
    'nav.trackrecord': 'REALIZZAZIONI',
    'nav.intelligence': 'INTELLIGENCE',
    'nav.method': 'ABOUT US',
    'nav.contact': 'Contact',

    'hero.title': 'Building Value, Designing Tomorrow',
    'hero.techBadge': 'Native AI & Smart Home Standard',
    'hero.cta': 'Discover Collections',

    'collection.techBadge': 'Travelli Intelligence Integrated',

    'home.intro': 'Beyond General Contracting. Transforming architectural visions into lasting real estate assets.',

    'projects.title': 'Featured Projects',
    'projects.subtitle': 'Selected portfolio of excellence in real estate development',
    'projects.signature.status': 'PRESTIGE COLLECTION',
    'projects.villa.tagline': 'Experience True Quality',
    'projects.villa.desc': 'A masterful restoration blending history with modern comfort on the Florentine hills.',
    'projects.casa.tagline': 'Living Beyond Standards',
    'projects.casa.desc': 'Exclusive residence in the city center, where design meets art.',
    'projects.borgo.tagline': 'Delivery 2026',
    'projects.borgo.desc': 'A residential complex immersed in nature, at the gates of Chianti.',

    'method.title': 'The Travelli Method',
    'method.subtitle': 'An integrated approach combining architectural vision, financial rigor, and operational excellence',
    'method.acquisition': 'Acquisition',
    'method.acquisition.desc': 'Strategic identification of high-potential real estate opportunities.',
    'method.design': 'Design',
    'method.design.desc': 'Collaboration with prestigious architecture firms for unique visions.',
    'method.construction': 'Development',
    'method.construction.desc': 'Integrated management of construction process with highest quality standards.',
    'method.management': 'Asset Management',
    'method.management.desc': 'Continuous value enhancement and long-term asset management.',
    'method.since': 'Since 2010',
    'method.value': 'Total value of developments completed',

    'method.hero.title': '30 Years of Construction and Development',
    'method.hero.subtitle': 'A legacy of construction excellence looking to the future',
    'method.stats.years': 'Years of History',
    'method.stats.projects': 'Completed Projects',
    'method.stats.delivered': 'Delivered on Time',
    'method.roots.label': 'OUR HISTORY',
    'method.roots.title': 'Our Roots',
    'method.roots.text1': 'Founded in 1994, Travelli has navigated three decades of real estate evolution. From a construction company focused on conservative restoration to an integrated Developer.',
    'method.roots.text2': 'Our experience extends from the recovery of listed historical buildings to the realization of modern residential complexes, always maintaining the highest technical rigor and attention to detail that distinguishes us.',
    'method.restoration.title': 'Conservative Restoration',
    'method.restoration.subtitle': 'Our specialization in listed buildings and historical recovery',
    'method.restoration.quote': 'Recovering the past requires more technique than building the new. Our experience with listed buildings is the guarantee of our construction quality.',
    'method.restoration.expertise1.title': 'Listed Buildings',
    'method.restoration.expertise1.desc': 'Thirty years of experience in restoring buildings subject to monumental and landscape constraints, in compliance with Superintendence regulations.',
    'method.restoration.expertise2.title': 'Traditional Techniques',
    'method.restoration.expertise2.desc': 'Specialized craftsmen in historical construction techniques, from Venetian stucco to fresco decorations.',
    'method.restoration.expertise3.title': 'Modern Comfort',
    'method.restoration.expertise3.desc': 'Invisible integration of modern systems and technologies while respecting original structures and historical context.',
    'method.restoration.expertise4.title': 'Value Enhancement',
    'method.restoration.expertise4.desc': 'Transformation of historical buildings into prestigious real estate assets, preserving their cultural value while increasing their economic worth.',
    'method.governance.label': 'LEADERSHIP',
    'method.governance.title': 'Continuity & Vision',
    'method.governance.subtitle': 'A team of professionals with decades of experience in real estate',
    'method.governance.team': 'A workforce of 50 professionals dedicated to excellence',

    'method.board.title': 'The Board',
    'method.board.subtitle': 'The Travelli Family',
    'method.board.roberto.name': 'Roberto Travelli',
    'method.board.roberto.title': 'Founder',
    'method.board.roberto.desc': 'The beginning of the Travelli story. He represents the solid roots from which the company was born. His work ethic forms the company\'s moral DNA and the indelible imprint guiding new generations.',
    'method.board.enrico.name': 'Enrico Travelli',
    'method.board.enrico.title': 'CEO & Head of Development',
    'method.board.enrico.desc': 'The dynamic evolution of the brand. Leads development strategy with an international vision. His focus is transforming spaces into unique living experiences, integrating contemporary design, sustainability, and smart technologies.',
    'method.board.elisa.name': 'Elisa Travelli',
    'method.board.elisa.title': 'CFO & Finance Control',
    'method.board.elisa.desc': 'The governance of numbers and strategy. Ensures the company\'s economic solidity and every single operation. Her rigorous planning ensures each project rests on transparent, concrete, and sustainable financial foundations.',

    'method.structure.label': 'OUR STRENGTH',
    'method.structure.title': '50 Direct Employees',
    'method.structure.subtitle': 'The guarantee of quality and certain timelines',
    'method.structure.desc1': 'Unlike many operators in the sector, Travelli can count on a workforce of 50 direct employees. No subcontracting, no occasional collaborations: a stable and dedicated team.',
    'method.structure.desc2': 'This means total control over every phase of the project, from design to delivery. It means certain timelines, consistent quality, and the certainty that every detail receives the attention it deserves.',
    'method.structure.benefit1': 'Total Quality Control',
    'method.structure.benefit1.desc': 'Every process is carried out by trained and certified internal staff',
    'method.structure.benefit2': 'Guaranteed Timelines',
    'method.structure.benefit2.desc': 'No dependency on external suppliers or unexpected delays',
    'method.structure.benefit3': 'Direct Responsibility',
    'method.structure.benefit3.desc': 'A single point of contact for the entire construction process',

    'method.process.label': 'OUR APPROACH',
    'method.process.title': 'The Integrated Method',
    'method.process.subtitle': 'From acquisition to sales: a complete process',
    'method.process.step1': 'Acquisition',
    'method.process.step1.desc': 'Strategic identification of high-potential real estate opportunities in premium locations',
    'method.process.step2': 'Design',
    'method.process.step2.desc': 'Architectural development with prestigious firms, maximizing value and livability',
    'method.process.step3': 'Construction',
    'method.process.step3.desc': 'Realization with internal workforce, constant quality control and certain timelines',
    'method.process.step4': 'Sales',
    'method.process.step4.desc': 'Direct sales with personalized assistance from viewing to closing',

    'method.team.label': 'MANAGEMENT & OPERATIONS',
    'method.team.title': 'Management & Coordination',
    'method.team.subtitle': 'An organizational structure coordinating over 50 direct employees. Our management ensures total control of every phase, from material procurement to key delivery.',
    'method.team.coo.title': 'Chief Operating Officer (COO)',
    'method.team.coo.desc': 'General supervision of construction sites and coordination of operational teams.',
    'method.team.pm.title': 'Senior Project Manager',
    'method.team.pm.desc': 'Technical management of complex projects and interface with Construction Management.',
    'method.team.sales.title': 'Sales Manager',
    'method.team.sales.desc': 'Responsible for sales and customer experience.',
    'method.team.procurement.title': 'Procurement Manager',
    'method.team.procurement.desc': 'Supplier selection and incoming material quality control.',
    'method.team.design.title': 'Head of Design',
    'method.team.design.desc': 'Architectural concept development and attention to finishing details.',
    'method.team.safety.title': 'Safety & Quality Manager',
    'method.team.safety.desc': 'Ensuring regulatory compliance and Travelli construction standards.',

    'method.management.title': 'Key Management',
    'method.management.subtitle': 'The Operational Leaders',
    'method.management.coo.name': 'Eng. [Full Name]',
    'method.management.coo.title': 'Chief Operating Officer (COO)',
    'method.management.coo.desc': 'Coordinates operational teams and logistics of our 50 employees, ensuring certain deadlines and site safety.',
    'method.management.pm.name': 'Eng. [Full Name]',
    'method.management.pm.title': 'Senior Project Manager',
    'method.management.pm.desc': 'The connection between design and execution. Manages the bureaucratic and technical complexity of every project.',
    'method.management.sales.name': '[Full Name]',
    'method.management.sales.title': 'Sales Manager',
    'method.management.sales.desc': 'Accompanies our clients from the first visit to the deed of sale, offering dedicated and personalized assistance.',

    'footer.subscribe': 'Subscribe',
    'footer.insights': 'Receive market insights and exclusive opportunities',
    'footer.navigation': 'Navigation',
    'footer.home': 'Home',
    'footer.collections': 'Collections',
    'footer.company': 'Company',
    'footer.about': 'About Us',
    'footer.careers': 'Careers',
    'footer.privacy': 'Privacy Policy',
    'footer.cookies': 'Cookie Policy',
    'footer.legal': 'Legal Notes',
    'footer.vat': 'VAT ID',

    'signature.title': 'TRAVELLI PRESTIGE',
    'signature.subtitle': 'The Pinnacle of Living.',
    'signature.intro': 'The Prestige collection represents absolute excellence in luxury real estate. Iconic projects that redefine the concept of exclusive living.',
    'signature.cta': 'Request Private Viewing',
    'signature.appointment': 'By invitation only • Confidential consultation',

    'urban.title': 'TRAVELLI LIVING',
    'urban.subtitle': 'Contemporary comfort for the changing city.',
    'urban.cta': 'DISCOVER PROJECTS',
    'urban.section.title': 'Our Developments',
    'urban.section.subtitle': 'Urban residences designed for contemporary lifestyle, where technology and comfort meet.',
    'urban.concept.title': 'The Living Concept',
    'urban.concept.subtitle': 'Innovation, sustainability, and connectivity at the heart of our residential vision.',
    'urban.feature.sustainability': 'Sustainability',
    'urban.feature.sustainability.desc': 'LEED certified buildings with solar panels and energy recovery systems',
    'urban.feature.smart': 'Smart Connection',
    'urban.feature.smart.desc': 'Advanced home automation, fiber optics, and integrated management app',
    'urban.feature.mobility': 'Soft Mobility',
    'urban.feature.mobility.desc': 'Bike sharing, electric charging stations, and metro/tram connection',
    'urban.project.cta': 'DISCOVER THE PROJECT',
    'urban.visit.cta': 'BOOK A VISIT',

    'collection.signature.title': 'TRAVELLI\nPRESTIGE',
    'collection.signature.desc': 'The art of living. Unique projects, without compromise.',
    'collection.signature.cta': 'Discover Prestige',
    'collection.urban.title': 'TRAVELLI\nLIVING',
    'collection.urban.desc': 'The evolution of contemporary living. Smart, connected, essential.',
    'collection.urban.cta': 'Discover Living',

    'intelligence.badge': 'PROPRIETARY TECHNOLOGY',
    'intelligence.title': 'TRAVELLI INTELLIGENCE',
    'intelligence.subtitle': 'Beyond Home Automation. The home that thinks with you.',
    'intelligence.card1.title': 'Smart Living & Control',
    'intelligence.card1.desc': 'Total environment management. Lights, climate, and security controlled from a single intuitive interface, wherever you are.',
    'intelligence.card2.title': 'AI & Energy Efficiency',
    'intelligence.card2.desc': 'Predictive algorithms that optimize consumption based on your real habits. Luxury means not wasting.',
    'intelligence.card3.title': 'Active Security',
    'intelligence.card3.desc': 'Integrated surveillance systems and environmental sensors for discreet but constant protection.',
    'intelligence.cta': 'Discover the Technology Standard',

    'intelligence.hero.title': 'Travelli Intelligence',
    'intelligence.hero.subtitle': 'The smart home is not an option. It\'s standard in every project.',

    'intelligence.features.title': 'What the System Includes',
    'intelligence.features.subtitle': 'A complete integrated home automation platform designed for daily comfort and security',
    'intelligence.features.climate.title': 'Smart Climate Control',
    'intelligence.features.climate.desc': 'Room-by-room temperature control with energy-saving algorithms',
    'intelligence.features.lighting.title': 'Intelligent Lighting',
    'intelligence.features.lighting.desc': 'Personalized lighting scenes and remote control for every room',
    'intelligence.features.security.title': 'Integrated Security',
    'intelligence.features.security.desc': 'Alarms, video cameras, and motion sensors managed in a single system',
    'intelligence.features.entertainment.title': 'Multiroom Audio/Video',
    'intelligence.features.entertainment.desc': 'Entertainment distributed in all rooms with centralized control',
    'intelligence.features.energy.title': 'Energy Monitoring',
    'intelligence.features.energy.desc': 'Real-time consumption tracking and automatic optimization',
    'intelligence.features.app.title': 'Dedicated Mobile App',
    'intelligence.features.app.desc': 'Complete control from iOS and Android smartphone wherever you are',
    'intelligence.features.scenes.title': 'Predefined Scenes',
    'intelligence.features.scenes.desc': 'Home, Night, Vacation modes activatable with one touch',
    'intelligence.features.ai.title': 'Artificial Intelligence',
    'intelligence.features.ai.desc': 'Learning your habits to optimize comfort and efficiency',

    'intelligence.standard.title': 'Standard in Every Project',
    'intelligence.standard.subtitle': 'Not an expensive upgrade, but an integral part of every Travelli residence. Technology is the new living standard.',
    'intelligence.standard.point1.title': 'Pre-installed as Standard',
    'intelligence.standard.point1.desc': 'Every apartment is delivered with the complete system already configured and tested',
    'intelligence.standard.point2.title': 'Dedicated Support',
    'intelligence.standard.point2.desc': 'Technical support and personalized training at delivery',
    'intelligence.standard.point3.title': 'Continuous Updates',
    'intelligence.standard.point3.desc': 'The system evolves over time with new features via software',

    'intelligence.landing.hero.title': 'TRAVELLI INTELLIGENCE',
    'intelligence.landing.hero.subtitle': 'Your home is a living organism. An integrated ecosystem of AI and Home Automation that learns, protects, and anticipates.',
    'intelligence.landing.nativo.title': 'DIGITAL NATIVE',
    'intelligence.landing.nativo.desc': 'Unlike traditional home automation installed after construction, the Travelli Intelligence system is wired into the building\'s DNA during construction. Invisible, reliable, eternal.',
    'intelligence.landing.services.title': 'THE 4 SYSTEM PILLARS',
    'intelligence.landing.climate.title': 'Predictive Climate',
    'intelligence.landing.climate.desc': 'Artificial intelligence cross-references real-time weather data with your habits. The house self-regulates in advance, guaranteeing perfect comfort and zero waste.',
    'intelligence.landing.circadian.title': 'Circadian Lighting',
    'intelligence.landing.circadian.desc': 'Light follows the biological cycle of the sun. Cool tones for morning energy, warm amber tones for evening relaxation. To live in harmony with your natural rhythm.',
    'intelligence.landing.monitor.title': 'Structural Self-Diagnostics',
    'intelligence.landing.monitor.desc': 'Integrated sensors constantly monitor water and electrical systems. The system detects anomalies and micro-leaks sending preventive alerts before they become failures.',
    'intelligence.landing.security.title': 'Active Security',
    'intelligence.landing.security.desc': 'The system distinguishes between guests, family, and intruders. Simulated presence scenarios when you\'re on vacation to deter any external intentions.',
    'intelligence.landing.cta.text': 'The future is already in the specs.',
    'intelligence.landing.cta.button': 'Request Technical Specifications',

    'trackrecord.hero.title': '30 Years of Excellence',
    'trackrecord.hero.subtitle': 'From conservative restoration to new constructions. Our history built stone by stone.',
    'trackrecord.filter.all': 'ALL',
    'trackrecord.filter.restauro': 'CONSERVATIVE RESTORATION',
    'trackrecord.filter.residenziale': 'RESIDENTIAL',
    'trackrecord.category.restauro': 'Historical Restoration',
    'trackrecord.category.residenziale': 'New Construction',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('IT');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.IT] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
